name: eco_disposal_app
description: 폐의약품/폐건전지 촬영 인식 및 수거함 길안내 앱
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  geolocator: ^13.0.1
  cloud_firestore: ^5.4.3
  firebase_core: ^3.6.0
  kakao_map_plugin: ^1.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
